github-push-issues.py: Decode bytes from zip/tar files
This fixes Python 3 errors like:

  Traceback (most recent call last):
    File "./github-push-issues.py", line 325, in <module>
      template_root=args.template_root)
    File "./github-push-issues.py", line 280, in add_issues
      milestone.load(stream=f)
    File "./github-push-issues.py", line 127, in load
      self.title = stream.readline().strip().strip('#').strip()
  TypeError: Type str doesn't support the buffer API

which you get if the opener returns a binary-mode file-like object.

I'm currently hardcoding UTF-8 as the encoding, but we can try
auto-detecting it or an optional argument if we want more flexibility
later.